### ISSUE TITLE
Add versions to docker image in Github workflow 

### ISSUE THREAD

**Issue by maidul98** [Infisical/infisical#159]
Currently, the workflow that generates the Docker images only have tag latest. I think this limites our ability to roll back to a specific image since all tags have latest tag. Having some kind of incremental versioning to the docker images pushed to docker hub would be great.

**Comment by cerrussell** [comment]
There are lots of Actions available to pull version tags and increment them. Or are you saying that there is currently no useable versioning metadata being generated anywhere, rather than it just not populating to docker hub? If so, there are also Actions that could be integrated to start doing this. Sorry I'm being so vague, I just can't tell for sure since sometimes the latest tag is used but the actual metadata is autogenerated.

**Comment by maidul98** [comment]
I believe we do not have any other metadata other than latest tag. Here is the workflow we use currently https://github.com/Infisical/infisical/blob/main/.github/workflows/docker-image.yml 

These then get pushed to dockerhub here https://hub.docker.com/r/infisical/backend and here https://hub.docker.com/r/infisical/frontend

If you would like to take a crack at this, let us know!

**Comment by cerrussell** [comment]
Yeah, I'm interested in helping out with this.

**Comment by maidul98** [comment]
Awesome, i'll assign it to you

**Comment by cerrussell** [comment]
Do you want to create a separate branch for me to submit the pull request?

**Comment by maidul98** [comment]
I believe you have to fork the repo and once you commit changes to your forked version, there will be an option to create a PR from your forked repo to the main repo

**Comment by cerrussell** [comment]
Yes, I've done all that, just wasn't sure if you wanted the request to go straight to main.

**Comment by maidul98** [comment]
https://github.com/Infisical/infisical/pull/168

**Comment by maidul98** [comment]
Task complete, thank you @cerrussell !
