### ISSUE TITLE
Propagate secret reference changes to downstream triggers

### ISSUE THREAD

**Issue by html5maker** [Infisical/infisical#1786]
### Describe the bug
Variable with a link to another variable is not synced with bitbucket (cloud integration)

### To Reproduce
1. Create a folder with the name "**bitbucket**"
2. Create a bitbucket integration (for the "**bitbucket**" folder)
<img width="1254" alt="Screenshot 2024-05-06 at 18 59 22" src="https://github.com/Infisical/infisical/assets/27346151/4a9c470f-1020-4f80-a01d-f2256d80e4c1">
3. Create 2 variables **VAR1** in the root folder and **VAR2** in the "**bitbucket**" folder
4. VAR1 value set to `something`, **VAR2** value set to `test${prod.VAR1}`

### Expected behavior
Try to change the **VAR1** value, expected result is that **VAR2** will be synced with bitbucket once **VAR1** is updated.
Current result - **VAR2** is not synced with bitbucket after **VAR1** value change.

### Screenshots
<img width="482" alt="image" src="https://github.com/Infisical/infisical/assets/27346151/a49c3b8a-c68f-4f10-9eab-6ff0409ba1b8">
<img width="574" alt="Screenshot 2024-05-06 at 19 09 50" src="https://github.com/Infisical/infisical/assets/27346151/78fe51f0-dedf-4abc-853e-9e84424f40fd">

### Platform you are having the issue on:
infisical cloud
bitbucket integration

**Comment by akhilmhdh** [comment]
Hey @html5maker 

This is now possible with our latest update.

As project admin kindly go to `Project Settings` and click on `Index Secret Reference` button
![Screenshot 2024-05-15 at 11 26 24 AM](https://github.com/Infisical/infisical/assets/31166322/61266812-7edd-4343-a2d8-4701e16c2dd4)

This is a one time action, so that infisical knows the secret references you have made in the existing secrets and the integrations to be triggered based on that. 

After that all your secret references should trigger integration sync.
