### ISSUE TITLE
Projects Created via API not visible in webapp/UI on a self-hosted instance in Kubernetes

### ISSUE THREAD

**Issue by bojanraic** [Infisical/infisical#2105]
### Describe the bug

Making API requests to create projects with an Universal Machine Identity acting as org-wide member succeeds, yet the projects are not visible in the application/UI. 
The records are added to the `projects` table in the db, so something must be missing before they can be displayed by the application

### To Reproduce
1. Create a UMI and add it to an organization as Member
2. Create a client ID and secret for the UMI
3. Use [Login endpoint](https://infisical.com/docs/api-reference/endpoints/universal-auth/login) to get a bearer token with the client id and secret from above
4. Using the bearer token from above, create a project via curl as described [here]( https://infisical.com/docs/api-reference/endpoints/workspaces/create-workspace)
5. View org dashboard - shows no projects created in previous steps
6. Go to db and find project IDs manually. 
7. Load the project URL with project ID in the browser directly {`/:project-id/secrets/overview`}- error page is shown: Oops, something went wrong

### Expected behavior
Created projects should be visible on the associated organization's overview page in the web app/UI. 

### Platform you are having the issue on:
Self-hosted Kubernetes v1.29.6, Infisical Version: v0.74.0-postgres via Helm chart, external postgres, external redis (not installed via the same chart)

**Comment by akhilmhdh** [comment]
@bojanraic This is expected, because when you create project with machine identity only that machine identity is part of the project and no one else thus, you won't be able to see it in dashboard.

To add members like the user your using in dashboard [use the invite member api endpoint](https://infisical.com/docs/api-reference/endpoints/project-users/invite-member-to-workspace).

We are planning to soon have a admin view of all the projects and its details.
