### ISSUE TITLE
When working with multiple organisations be able to only log in once via CLI

### ISSUE THREAD

**Issue by jinbe** [Infisical/infisical#2191]
This is with a self-hosted instance.

### Feature description
I have a user that is the owner of several organisations. I'm using this to seperate out secrets for the various organisations I contract for. At the moment I need to log in again and select the correct organisation which makes it difficult to multi-task in several environments at once.

### Why would it be useful?
Saves me having to constantly log in.

### Additional context
Self-hosted.

**Comment by akhilmhdh** [comment]
@jinbe This is an expected behavior due to security restrictions we have taken, changing this would be quite tricky as there lot of decisions taken over this one. This is majorly aligned due to various kinds of org authentication restriction that could happen like SSO, SAML. etc and the machine identity communication.
