### ISSUE TITLE
i can't inject env to `echo` used inline.

### ISSUE THREAD

**Issue by gustawdaniel** [Infisical/infisical#2854]
When i type

```
infisical secrets --env=prod --path=/
```

then i can easy see table with correct value of `OPENAI_API_KEY` but typing

```
infisical run --env=prod --path=/ -- echo ${OPENAI_API_KEY}
```

i see only log and empty message.

```
1:34PM INF Injecting 9 Infisical secrets into your application process

```

more context:

I added script `app.js` with line

```
console.log(process.env)
```

and calling this script works as should:

```
infisical run --env=prod --path=/ -- node app.js | grep OPENAI
1:39PM INF Injecting 9 Infisical secrets into your application process
  OPENAI_API_KEY: 'sk-xxx',
```

so my issue is about usage of echo inline, not injecting to real app.

**Comment by akhilmhdh** [comment]
@gustawdaniel This is expected. This is not an issue with infisical or your echo command. If you change the inline echo command to a shell file and execute it like `infisical run --env=prod --path=/ -- echo.sh` it would work. 

The above inline command is not working because the secret expansion is something your shell is doing. It happens before even before your command is executed
