### ISSUE TITLE
Build frontend within image build process and inject envars into containers at runtime

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#36]
### Feature description

Instead of building the frontend separately from the image, Infisical should pre-build the frontend within the image build process and make it so that envars can be injected into containers at runtime.

### Why would it be useful?

This would expedite the frontend deployment process and reduce downtime between deployments by 1-2 mins.

### Additional context

The difficulty stems from Next.js baking environment variables in at build time which wouldn't work for self-hosting since everyone uses their own environment variables; passing in environment variables into Next.js at runtime results in undefined environment variables.

**Comment by reginaldbondoc** [comment]
Hi @dangtony98,

I am taking a jab at this and I would like to take a different approach.

Instead of going for runtime access (which will prevent optimization of built frontend package), let's remove the dependency. From the current frontend codebase, I see these:
1. Only the environment variable `NEXT_PUBLIC_WEBSITE_URL` is actually being used
2. One is in `next.config.js` for CSP and we can use `self` value for that - you already merged the change re: this
3. Another is usage as `PATH` const

I prepared a pull request to fulfill item 3 above. If that is fine, then the only remaining thing is to actually use the frontend image, no need for environment variables at all.

Unless you see the need for environment variable at runtime? In that case, we'll be forced to use a different approach, but that will prevent frontend build optimization. Until then, maybe my approach here will suffice?

**Comment by dangtony98** [comment]
Hey egi!

I checked the PR and it looked good to me! — Good optimizations to frontend by removing `PATH` and `NEXT_PUBLIC_WEBSITE_URL`.

That said, I think there's still one variable that's `NEXT_PUBLIC_TELEMETRY_ENABLED` that's being used on the frontend for people to opt-out of telemetry at run-time; the remaining variables can be baked into the image build for sure.

**Comment by reginaldbondoc** [comment]
Oh, you're right!

In that case, I will continue on finding a solution to this. 🙇

**Comment by reginaldbondoc** [comment]
[Solution](https://github.com/Infisical/infisical/pull/80) has been accepted and merged.
