### ISSUE TITLE
Self-hosted instance not sending email

### ISSUE THREAD

**Issue by drtobbyas** [Infisical/infisical#379]
### Describe the bug
Self-hosted instance on Kubernetes does not send emails.

### To Reproduce
1. Set up a self-hosted instance on Kubernetes as described in the documentation
2. Add your valid SMTP details to the values.yaml file
3. Go to your ingress domain and attempt to sign-up.
4. The sign-up email will not be sent to the provided email address.

### Expected behavior
The sign-up email should be sent to the email address provided for sign-up

### Platform you are having the issue on:
Tested on kubernetes

### Additional context
The token hash appear to be logged in the MongoDB database. This gives an indication that the sign-up token was probably generated but not sent to the user.

**Comment by dangtony98** [comment]
Hey @drtobbyas!

Which SMTP server are you using? You can check out the docs [here](https://infisical.com/docs/self-hosting/configuration/email) for how to configure mailing with your own SMTP server.

We currently have confirmed support for SendGrid, Mailgun, AWS SES, and SocketLabs — Happy to add another SMTP server option if you're using something else.

**Comment by drtobbyas** [comment]
I tried zohomail smtp with a custom domain. It didn't work. I also tried troubleshooting with mailtrap, but It didn't work either.

**Comment by dangtony98** [comment]
I see. Would you be okay with using one of the existing supported options: SendGrid, Mailgun, AWS SES, or SocketLabs?

If not, I can have support for Zohomail done for you by tomorrow!

**Comment by drtobbyas** [comment]
It would be awesome if it can support any (if possible) SMTP server. Many users use different email services including Cpanel kind of hosting.

**Comment by dangtony98** [comment]
@drtobbyas The issue is that some SMTP servers come with some additional needed configuration on our end (e.g. incompatible TLS version), so they don't always work out of the box; this is why we typically have to confirm SMTP compatibility for each one and provide instructions.

There's actually a whole separate issue to build out support for all/most SMTP servers [here](https://github.com/Infisical/infisical/issues/346).

I'll add in support for Zohomail in the next few hours for you!

**Comment by drtobbyas** [comment]
ok, good. Thanks

**Comment by dangtony98** [comment]
Hey @drtobbyas!

I've just pushed out a new Docker image with support for Zoho Mail — I've added docs for it [here](https://infisical.com/docs/self-hosting/configuration/email) as well.

**Comment by WladyX** [comment]
I have a custom postfix server and i am unable to send emails.
I have tried both with SECURE and without, but i don't see any connection in the mail logs.
Is it possible to create users without sending email?

**Comment by insertish** [comment]
I run a https://maddy.email/ server and I just ran into this issue as well.

If I try to send mail over port 587 with SMTP_SECURE=true:

![image](https://user-images.githubusercontent.com/38285861/224120113-840e7370-5b86-4328-99cc-e1642bd41843.png)

With other configurations of ports and SMTP_SECURE, it seems to connect fine but no email is ever actually sent, the most I see in the mail server logs are the initial authentication:
```
maddy_1          | submission: 220 -snip-.revolt.wtf ESMTP Service Ready
maddy_1          | -snip-
maddy_1          | submission: AUTH PLAIN -snip-
maddy_1          | submission: 235 2.0.0 Authentication succeeded
maddy_1          | submission: QUIT
maddy_1          | submission: 221 2.0.0 Bye
```

But beyond that, I never see it talk with the mail server again.

I'm not sure if it's intentional but pressing resend (submitting the sign up page does this too) throws 404:

![image](https://user-images.githubusercontent.com/38285861/224123533-b0ebb053-f3e8-4e8a-9279-122817874e0f.png)
![image](https://user-images.githubusercontent.com/38285861/224123558-aea62313-5747-49fa-ac29-cf00d7d843b7.png)

**Comment by byjokese** [comment]
On my case when using Amazon SES, with `SMTP_SECURE` to `true` and `SMTP_PORT` to `587`, it gives an 500 Error, and Sentry reports:
![image](https://github.com/Infisical/infisical/assets/5951126/167b0ca2-06bd-4e96-8f71-de42c7edae7f)

**Comment by akhilmhdh** [comment]
Closing as stale. This should be now possible with SMTP configuration in env

https://infisical.com/docs/self-hosting/configuration/envars?ref=alphasec.io#email-service
