### ISSUE TITLE
Secrets Operator helm chart deploys a service with name longer than 63 characters

### ISSUE THREAD

**Issue by ianwesleyarmstrong** [Infisical/infisical#403]
### Describe the bug
The `secrets-operator` helm chart can create a name for the metrics service that is longer than kubernetes can handle.

### To Reproduce
1. Create a helm release named `infisical-dev`
2. All other resources will create successfully

### Expected behavior
The helm template should use a shorter name, or truncate in the case 

### Screenshots
If applicable, add screenshots to help ex
![Screenshot 2023-03-04 at 6 44 58 PM](https://user-images.githubusercontent.com/24705212/222933719-e231349a-78c8-4402-b4b9-be651cc4e78f.png)
plain your problem.

### Platform you are having the issue on:
K8s

### Additional context
I'll also open up a PR with a fix depending on what approach is advised!

**Comment by maidul98** [comment]
Hey Ian, thank you for bringing this to our attention. The issue is that the auto-generated release name is too long. We solve this issue by truncating everything past 63 characters in our other chart: https://github.com/Infisical/infisical/blob/main/helm-charts/infisical/templates/_helpers.tpl#L5

We need to do the same for this as well. To create our Kubernetes manifests/helm chart for the operator, we use Kubebuilder. To fix this, I believe we will need to modify our Kubebuilder settings to achieve this behavior. If you are familiar with Kubebuilder, please send a PR. Otherwise, I can look into making this change.

As a temporary fix, please set the release name manually to something shorter than 63 characters. Let me know if this fixes your issue for now

**Comment by ianwesleyarmstrong** [comment]
@maidul98 I'm not familiar, so it would probably be best for you to take it up. Sadly the release name is auto-generated through the ArgoCD app-of-apps pattern, so it's hard for me to shorten the release date at this time. The actual functionality of the chart is working - just the metrics server svc doesn't deploy

**Comment by maidul98** [comment]
The issue should be fixed. It had to do with our auto helm package generation Kustomize. Since we cannot control how the template files are generated, I have manually set the length taking into account the text after the named template https://github.com/Infisical/infisical/blob/main/helm-charts/secrets-operator/templates/metrics-service.yaml#L4

Please update your helm chart and try to install again. Let us know if it works for you

**Comment by ianwesleyarmstrong** [comment]
Looks like it did the trick! It now gets truncated to this:

`infisical-dev-s-controller-manager-metrics-service`
