### ISSUE TITLE
Ability to replicated secrets to selected environments upon saving in one

### ISSUE THREAD

**Issue by jerriclynsjohn** [Infisical/infisical#419]
### Feature description
The user should be able to replicate the new set of secrets that they add to the current environment to all/any other environment/s present.

### Why would it be useful?
Right now the user should manually copy repetitive secrets to all the environments, which is counter-productive as most of the time at least having the Key of the secrets getting copied will save a lot of time

### Additional context
We should be able to take inspiration from Doppler regarding this user experience. Kindly check this screenshot to see how it is done in Doppler when a user tries to save a secret in one environment.
![Screenshot 2023-03-10 084551](https://user-images.githubusercontent.com/3236669/224217343-29d7b2e8-dc4f-4fba-81be-d61aae5f39e3.png)

**Comment by parthvnp** [comment]
Is help still needed on this issue? I would be happy to work on it!

**Comment by akhilmhdh** [comment]
Hey @jerriclynsjohn  we have recently released this feature, which allows you to copy secret from another environment and then modify it as you wish. 

The overview page will have another create secret feature coming soon. We cannot provide the above method as it is  because of the difference in which how infisical works and doppler works. But we do think the new copy secret will be a quite good solution to solve this above matter.

We are closing this issue, as this is solved. Feel free to open it, if its not your looking for
