### ISSUE TITLE
Get by tags not working when connected by token

### ISSUE THREAD

**Issue by maciej-gawlas** [Infisical/infisical#472]
### Describe the bug
I'm using Infisical in CI when I want to get only secrets with tag backend. I'm using token to get secrets from Test env. Unfortunately all secrets are returned. There is no issue when I log in. In both places I use infisical version 0.3.7.

### To Reproduce
1. Connect to self hosted infisical with token
2. Try to get secrets with tag `infisical secrets --tags=backend`
3. All secrets are returned

### Expected behavior
Only secrets associated with tag should be returned

### Screenshots
![image](https://user-images.githubusercontent.com/48756501/228806474-9459d2c2-dff5-4392-9abc-eb49bbbba969.png)

<img width="1192" alt="Screenshot 2023-03-30 at 12 12 34" src="https://user-images.githubusercontent.com/48756501/228806687-afbcf2d9-ad4a-4757-ad43-fcffd4a768cc.png">

**Comment by maidul98** [comment]
Hey @maciej-gawlas I'll take a look into this and get back to you

**Comment by maidul98** [comment]
The reason for this is because tags should be specifed during service token creation. This way the token can only access certin tags. While the backend for this is complete, the frontend is not yet done. 

We are in the midst of allowing users to create folders and adding permissioning on folders during service token creation. I think this will be more useful. I can update you once we are done: https://github.com/Infisical/infisical/pull/465

**Comment by maciej-gawlas** [comment]
Hi @maidul98 thanks for checking this. That task is what I was looking for! Thanks :)
BTW: Great work with this app, good luck!
