### ISSUE TITLE
docs: improve docs for setup github / gitlab / circle CI intégrations

### ISSUE THREAD

**Issue by fredleger** [Infisical/infisical#477]
### Feature description

The documentation for using github / gitlab etc .. intégrations are a bit short. Should be nice if you provide more instructions / example. My main questionning is about the callback url but i'm not even sure if it could work on self hosted.

### Why would it be useful?

For self hosting users who want to setup CI integrations

### Additional context

None

**Comment by dangtony98** [comment]
@fredleger Definitely will add that and keep you posted 🙂

In most cases, it should be easy to set up the various integrations (by just registering a new OAuth2 application in that integration) though some of them require more work like Azure.

**Comment by fredleger** [comment]
thanks @dangtony98 
what i have been trying to achieve (as a demo) : 
- created a new github oauth application
- added CLIENT_SECRET_GITHUB and CLIENT_ID_GITHUB both from the step above in backend env vars (through helm values and confirmed it worked)
- enable the Github action integration on my demo project (oauth seems to work)
- but the choice of repository is neither displayed got redirected to a blank page
- inspecting it from my browser seems that some urls call get 500 errors

screenshots:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/2778741/229732892-91aae840-c456-42ff-8b79-4ab432f73b92.png">

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/2778741/229733650-d5a4be6c-c965-41c8-bc8a-955dc93745af.png">

<img width="425" alt="image" src="https://user-images.githubusercontent.com/2778741/229734042-397190de-ecf2-4800-9b79-58804d199fbf.png">

**Comment by dangtony98** [comment]
Ah @fredleger can you try setting the redirect URL to `https://infisical.labs.wmars.party/integrations/github/oauth2/callback`?

**Comment by fredleger** [comment]
@dangtony98 how can we help here ? i can provide an k8s instance with access to it if that can help

**Comment by fredleger** [comment]
great. not a problem, just being impatient to test the feature.
thanxs for the good work here ;-)

**Comment by dangtony98** [comment]
Hmm @fredleger, I just tested the GitHub integration (1) locally and (2) via [Docker Compose](https://infisical.com/docs/self-hosting/deployment-options/docker-compose); it worked in both cases.

This required:
- Creating a new OAuth application in my Organization > Developer Settings > OAuth Apps with the right settings, in particular the authorization callback URL (see screenshot below).
- Obtaining the Client ID and generating a new Client Secret as part of the GitHub OAuth Application; the Client ID should be included as an environment variable for Infisical `CLIENT_ID_GITHUB` and `CLIENT_SECRET_GITHUB`.
- Starting up Infisical with correct environment variables.

<img width="568" alt="Screen Shot 2023-06-01 at 2 55 10 PM" src="https://github.com/Infisical/infisical/assets/25857006/0add374a-ee57-4d59-b271-d77a46557933">

It's possible to test this by, for example, running Infisical locally with the instruction in the [repository](https://github.com/Infisical/infisical).

I think we would need to check out your instance specifically or try to replicate the issue because it seems to work fine on my end.

**Comment by htdangkhoa** [comment]
any update on it, I got the same issue

**Comment by dangtony98** [comment]
Hey @htdangkhoa have you tried the steps above?

**Comment by htdangkhoa** [comment]
Hi @dangtony98 I tested with the latest version of the `docker-compose.yml` I see the same issue. So when I try to integrate with Github OAuth I see the API has an error with 500. I also tested on k8s helm with a single replica and 2 replicas, please help me check again.

Thanks

![Screen Shot 2023-06-05 at 01 56 19](https://github.com/Infisical/infisical/assets/15341301/c8f83693-11c6-40c4-9467-06231a26e07e)
![Screen Shot 2023-06-05 at 02 03 09](https://github.com/Infisical/infisical/assets/15341301/c2a83d80-6009-4fb6-8f18-5d874d07272c)

**Comment by ganga2166** [comment]
I was getting a blank page after integrated with Github 
<img width="1430" alt="Screenshot 2023-06-13 at 10 54 18 AM" src="https://github.com/Infisical/infisical/assets/80946904/782c7594-d738-4e66-8899-9cc1bfa3eda7">
<img width="1438" alt="Screenshot 2023-06-13 at 10 53 00 AM" src="https://github.com/Infisical/infisical/assets/80946904/73635381-d8de-42e6-baa8-521f8f0ee618">

**Comment by htdangkhoa** [comment]
Hi @dangtony98, any update for this?

**Comment by dangtony98** [comment]
Hi @htdangkhoa,

We're releasing an integrations page revamp this week actually, so I'll circle back here after that is merged.

**Comment by amanasterdio** [comment]
Hi @dangtony98  Any updates on the integrations page ?

**Comment by ganga2166** [comment]
Any update on this?

**Comment by dangtony98** [comment]
Hi everyone!

This issue should now be resolved with #903. I've added self-hosted setup/configuration docs for all integrations using OAuth2:

- [GitHub](https://infisical.com/docs/integrations/cicd/githubactions)
- [GitLab](https://infisical.com/docs/integrations/cicd/gitlab)
- [GCP Secret Manager](https://infisical.com/docs/integrations/cloud/gcp-secret-manager)
- [Vercel](https://infisical.com/docs/integrations/cloud/vercel)
- [Heroku](https://infisical.com/docs/integrations/cloud/heroku)
- [Netlify](https://infisical.com/docs/integrations/cloud/netlify)
- [Azure KV](https://infisical.com/docs/integrations/cloud/azure-key-vault)

Simply, for each of the above integrations, you have to configure an OAuth application and input its Client ID and Client Secret as environment variables for Infisical.

The remaining integrations shouldn't require any additional setup/configuration docs since they are API Key / Personal Access Token-based.

**Comment by Rajeev-2001** [comment]
@dangtony98 can I get same support for bitbucket integration on self-hosted?
