### ISSUE TITLE
Uploading More than 200 Secrets

### ISSUE THREAD

**Issue by rahb3rt** [Infisical/infisical#557]
### Describe the bug
When trying to upload more than 200 secrets the connection between the api and front end seems to time out. 

### To Reproduce
Try uploading a secret file with more than 200 secrets.

### Expected behavior
The number of secrets should not matter when uploading to the platform and should be able to process them all.

### Screenshots
n/a

### Platform you are having the issue on:
EKS

**Comment by delavegar25** [comment]
I suggest optimizing the API request, maybe optimize the API request by implementing pagination (for example: define the page size infisical wants) or divide them into smaller batches and upload them sequentially.

**Comment by neto210206** [comment]
Describe the bug

When trying to upload more than 200 secrets the connection between the api and front end seems to time out.

To Reproduce

Steps to reproduce the behavior:
Try uploading a secret file with more than 200 secrets.

Expected behavior

The number of secrets should not matter when uploading to the platform and should be able to process them all.

Platform you are having the issue on:

EKS

**Comment by ali-master** [comment]
@rahb3rt 
@delavegar25 

I checked the issue locally, and everything worked as well as desired. The problem may be fixed now.

**Comment by akhilmhdh** [comment]
Closing as its stale. We have now pagination and api is now much faster
