### ISSUE TITLE
Supabase integration doesn't work

### ISSUE THREAD

**Issue by mikestopcontinues** [Infisical/infisical#618]
### Describe the bug

I set up the integration with a valid auth token. Neither Infisical nor Supabase are alerting me to errors. And yet there are no secrets imported to Supabase.

### To Reproduce

1. Have secrets in the target Infisical env
2. Create a new integration with Supabase
3. Nothing happens

### Additional context

I checked the secrets table directly. Nothing there.

**Comment by dangtony98** [comment]
Hi @mikestopcontinues!

Is this issue related to Infisical Cloud or a self-hosted instance of Infisical?

Once synced, the environment variables can be checked via the Supabase CLI or accessible in edge functions like this: Deno.env.get(MY_SECRET_NAME).

**Comment by mikestopcontinues** [comment]
Hi Dan!

I do see the secrets when I run `supabase secrets list`. That's good!

However, I think the integration still needs to be updated. It seems that Supabase as a newer mechanism for secrets storage with features I would like to opt into. Here's the [docs](https://supabase.com/docs/guides/database/vault). And here's some screenshots that demonstrate what Infisical is doing is NOT landing the secrets in the "vault."

<img width="868" alt="Screenshot 2023-06-03 at 3 40 29 PM" src="https://github.com/Infisical/infisical/assets/150434/514d79c2-578e-40a4-88f8-08baabd6add4">
<img width="846" alt="Screenshot 2023-06-03 at 3 40 49 PM" src="https://github.com/Infisical/infisical/assets/150434/7a7f64c9-9ad1-41ef-bad9-6d9e47980714">

**Comment by dangtony98** [comment]
Hi @mikestopcontinues,

Gotcha. I believe that at the time of releasing the integration, Supabase Vault wasn't live yet.

I've since added the Supabase Vault integration to our [roadmap](https://www.notion.so/be2d2585a6694e40889b03aef96ea36b?v=5b19a8127d1a4060b54769567a8785fa). Given current ongoing initiatives, I'd expect this integration to be done sometime next quarter but I can also try to squeeze in time for it sooner.

**Comment by mikestopcontinues** [comment]
Thanks, I appreciate it! For the meantime, I'll manage. :)

**Comment by dangtony98** [comment]
Thanks @sheensantoscapadngan :)

**Comment by ChukwunonsoFrank** [comment]
hey @dangtony98 @mikestopcontinues ,

After reviewing the documentation from Supabase, it's safe to say that Vault is only accessible via the dashboard's UI and the SQL editor. Hence, no external API to enable integration with Infisical.

However, since Vault is still in beta as of writing, programmatic access via a REST API may be something to look forward to in Supabase's next feature release.

**Comment by mikestopcontinues** [comment]
Thanks for looking into it, @ChukwunonsoFrank. I'll keep an eye out for when it exits beta. :)

**Comment by dangtony98** [comment]
Closing this issue for now since we can't do anything about Supabase Vault not offering programmatic access via REST API.

We can re-open it in the future when it becomes possible to make this integration!
