### ISSUE TITLE
Professional features aren't immediately available after billing update.

### ISSUE THREAD

**Issue by JamesArthurHolland** [Infisical/infisical#637]
### Describe the bug
We just upgrade to professional from free tier. I can't add members. I've tried clearing the frontend cache etc. Still not working.

I also can't join the slack group because it autofills to be "@infisical.com" and my personal email didn't automatically get an invite to the slack channel. We don't use google or apple, so it has to be via email, which I can't do.

### To Reproduce
1. Create a new account.
2. Update the billing to "professional"
3. Try to add new members.

### Expected behavior
Professional features should be available instantly.

### Platform you are having the issue on:
Cloud

**Comment by dangtony98** [comment]
Hi @JamesArthurHolland, so sorry about this — We've received another report about this issue and are actively working on resolving this by end of day today.

Could you in the meantime:
- Log into the [customer portal](https://portal.infisical.com/auth/login) and checking to see if the correct plan is reflected there?
- Try joining this [Slack](https://infisical.com/slack); the Slack issue is strange — Perhaps you had the wrong link before?

**Comment by vmatsiiako** [comment]
Hi @JamesArthurHolland! This should be fixed now. Could you please confirm if it works for you?

**Comment by vmatsiiako** [comment]
By the way, you should be able to join Slack without @infisical.com email. Could you try using this link? https://join.slack.com/t/infisical-users/shared_invite/zt-1wehzfnzn-1aMo5JcGENJiNAC2SD8Jlg

**Comment by dangtony98** [comment]
This was fixed last week with revisions made to the member limit, project limit, and environment limit paywalls.

It may take a few minutes tops after upgrading/downgrading plans for the correct feature set to be reflected on Infisical Cloud due to caching to reduce excessive calls made to the license server but this shouldn't be a noticeable issue; the main issue which is returning the correct paywalls corresponding to the organization's existing plan has been addressed 😄
