### ISSUE TITLE
Updated secret value doesn't sync to Supabase

### ISSUE THREAD

**Issue by pascalmtts** [Infisical/infisical#823]
### Describe the bug
When updating the values of secrets, the updated value doesn't sync to Supabase when the Supabase integration is enabled.
Sync of new values does work.

### To Reproduce
1. Enable Supabase integration
2. Update a value of a secret
3. Get value in Supabase Edge function

### Expected behavior
Secrets should be kept in sync and update, when a value is updated. 

### Platform you are having the issue on:
Supabase

**Comment by akhilmhdh** [comment]
Ahh i see. #824 i think its caused due to this. We recently realized supabase, integrations is failing because there are some predefined environment variables that supabase rejects if changed. 

We are looking to find where these environments list to avoid mutating any of them. Will fix this within next few days.

**Comment by akhilmhdh** [comment]
hey @pascalmtts can you check once again this. If you self hosted kindly update the image, we have released a fix for this and your supabase integration should work now. 

Post Mortem Report

The issue was supabase `GET` secrets list was also giving its reserved secret in list. So we can do a `POST`operation over it but, you can't delete them as it will throw an error. We have fixed it by checking the supabase reserverd secret.

In coming release we will be soon moving integration sync to a queue system so that your dashboard and  integration will be decoupled. And proper error messages will be conveyed

**Comment by pascalmtts** [comment]
Looks good to me!
