### ISSUE TITLE
Add historical scan capability to github secret scanning app

### ISSUE THREAD

**Issue by maidul98** [Infisical/infisical#881]
### Feature description
Currently, only new commits are scanned for exposed secrets. This leaves secrets exposed in old commits hidden. Right after users add git repositories, we should iniate a scan of all available repositories.

### Why would it be useful?
This will he helpful because users can find out leaked secrets from past commits

### Additional context
The repo scan should be initiated here https://github.com/Infisical/infisical/blob/main/backend/src/ee/services/GithubSecretScanning/GithubSecretScanningService.ts#L21

The secret scanning makes use of our CLI scanning, more details about this can be found here https://infisical.com/docs/cli/scanning-overview

**Comment by daninge98** [comment]
I'm happy to have a look at this.

I imagine the part that might be tricky is if we get the notification of the installation over websocket before the user has been redirected to the secret-scanning page after the Github authorization flow (and therefore before we have linked the Github installation ID to the Infisical organization ID in our database). This means that when we receive the websocket installation notification, we wouldn't have a way to get the Infisical organisation ID in order to construct/write the GitRisks documents when the historical scan is complete

Maybe rather than write an Organization ID as part of GitRisks we should instead write the Installation ID, and then here (when we are querying the GitRisks): https://github.com/Infisical/infisical/blob/5b342409e3cf9edd039dd5e95d3422fb165f005b/backend/src/controllers/v1/secretScanningController.ts#L75 we can first lookup the Installation ID associated with the organization and then look up the GitRisks using that? It seems not great to have GitRisks hanging around in the database that potentially aren't owned by an organization though.

I guess another option is just to do the historical scan on the first commit after installation if we detect it hasn't been done before?

We could also just like `sleep(30)` in the installation scan and hope that the organization id <> installation id mapping gets populated by that time?

Maybe I'm just missing something and there is an easier way? Do you have any thoughts @maidul98?
