### ISSUE TITLE
[ENG-77] Set personal override secrets using CLI

### ISSUE THREAD

**Issue by decarbonise** [Infisical/infisical#892]
### Feature description
On the web view and using the REST API, we can set personal secrets. However, the CLI does not currently have an option to specify that we want to set a personal rather than shared secret: https://infisical.com/docs/cli/commands/secrets

### Why would it be useful?
Allows users to set personal secrets, which is already recognised as a valuable feature through the web GUI and REST API.

<sub>[ENG-77](https://linear.app/infisical/issue/ENG-77/set-personal-override-secrets-using-cli)</sub>

**Comment by vmatsiiako** [comment]
Also requested by: [https://infisical-users.slack.com/archives/C04BSBMQAQ7/p1694336580267499](https://infisical-users.slack.com/archives/C04BSBMQAQ7/p1694336580267499)

**Comment by Orang-utan** [comment]
Ditto to that -

A nice UX will also be user provide a local .env which can override certain variables from Infisical

**Comment by netaisllc** [comment]
I would pay BIG MONEY for this feature. 

**Why?**

In our particular use case, we store as dev-specific secrets what are essentially urls. The urls are 'callback points' used by the entire host of 3rd-party system our apps collaborates with. There are several.  Normally these values are "set-and-forget" values, but they always differ by dev. (Which is why we love Infisical.)

That said, it is all too common - for testing, repro, pair-coding, etc - to need to _temporarily_ override one's secret for a particular service. 

To have to login into the webapp, find the secret, carefully override it, make a mental not to "un-override it" just breaks the flow and makes everyone cranky and mean.  Well, maybe not the last part, but certainly it breaks the flow.

Our vote would be for a simple CLI rev that supported 'replacement' of an existing value.

If the key does not exists, error out. (That's on us to pre-add the key.)

We consider putting a "duration" on the override excessive and overly complicated for our case.

But devs be devs...

**Comment by mmclane** [comment]
I very much want to be able to use a local .env file to override values coming from infisical

**Comment by sheensantoscapadngan** [comment]
Hey all! This should be possible now in the latest release by doing something like the following:
`infisical secrets set KEY=value1 --type=personal` 

cheers!
